### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Xiong5Heng** [bchaiks/3D_Bin_Packing_Heuristics#1]
Hello,
Do you have an example or a documentation to show me how to run your code

**Comment by bchaiks** [comment]
Hi, 

I just put up a new branch called "Sample", which has a new version of the file "packing.py" that you should be able to run directly (it requires Numpy).  There is a sample input at the beginning of that file that you can edit.  The file "Test_Output.py" shows the output format.    

Most of the code on the main branch does not work, because I just started to work on refactoring it.

**Comment by Xiong5Heng** [comment]
Wonderful! Thanks for your work.

**Comment by bchaiks** [comment]
You're welcome!
